Retry
extreal-dev/Extreal.Integration.Chat.Vivox pull request #15
Opened 2023-02-10 03:15 UTC by kiyohome

# 何の変更を加えましたか？

# 何を確認しましたか?

## 実装

- [ ] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [ ] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [ ] 静的解析で問題が見つからないことを確認しました
- [ ] フレームワーク利用者が使うAPI（主にprivate以外）に C# ドキュメントを記述しました

## テスト

- [ ] 全ての自動テストが成功することを確認しました
- [ ] テストカバレッジが100%になることを確認しました
- [ ] サンプルがあるものはサンプルが動作することを確認しました

## 変更影響

- [ ] GuideのReleaseページに変更内容が追加されることを確認しました
- [ ] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
- [ ] GuideのLearningページに変更が反映されることを確認しました
- [ ] Sample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2023-02-13 02:56 UTC, sus-taguchi-t requested changes

2023-02-13 02:56 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                await UniTask.WaitUntil(() => LoginSession.State is LoginState.LoggedIn);
```csharp
await UniTask.WaitUntil(() => IsLoggedIn);
```

にした方が分かりやすいと思います。

2023-02-13 02:56 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                await UniTask.WaitUntil(() => IsLoggedIn);
`LoginAsync` で既に `IsLoggedIn` を待っているので、ここでこの処理を入れる必要はないと思います。

2023-02-13 02:56 UTC, sus-taguchi-t commented on Tests/Runtime/VivoxClientTest.cs
> +                appConfig.ApiEndPoint, appConfig.Domain, appConfig.Issuer, appConfig.SecretKey, vivoxConfig));
**ライブラリやテスト内容自体には関わらないです。**

ここの `ChatConfig` から `VivoxAppConfig` への接続が少し回りくどく感じました。
後のリファクタリングで修正した方がいいかもしれません。

2023-02-14 12:19 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +                await UniTask.WaitUntil(() => LoginSession.State is LoginState.LoggedIn);
Fixed!
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/15/commits/40a8edb1d394cca22a6ad65178d89479ebaa62d0

2023-02-14 12:22 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +                await UniTask.WaitUntil(() => IsLoggedIn);
Fixed!
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/15/commits/3e11c84347c2a6b405ad01f16d3baa4fd2a5844d

2023-02-14 12:31 UTC, kiyohome commented on Tests/Runtime/VivoxClientTest.cs
> +                appConfig.ApiEndPoint, appConfig.Domain, appConfig.Issuer, appConfig.SecretKey, vivoxConfig));
Fixed!
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/15/commits/25faa88a9208d11a24ab3c3bf2dc980014188dcb

2023-02-22 07:39 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                await UniTask.WaitUntil(() => LoginSession.State is LoginState.LoggedIn);
確認しました！

2023-02-22 07:39 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                await UniTask.WaitUntil(() => IsLoggedIn);
確認しました！

2023-02-22 07:41 UTC, sus-taguchi-t commented on Tests/Runtime/VivoxClientTest.cs
> +                appConfig.ApiEndPoint, appConfig.Domain, appConfig.Issuer, appConfig.SecretKey, vivoxConfig));
確認しました！

2023-02-28 00:45 UTC, sus-taguchi-t requested changes

2023-02-28 00:45 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        /// Arg: Final results of retry. True for success, false for failure.
results -> result

2023-02-28 00:45 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        private bool isLoginBlocking;
フィールドは 1 箇所にまとめないで良いでしょうか？

https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/blob/52c841c01a07c2188695bf96d3d5b46e763e0d9d/Runtime/VivoxClient.cs#L342
ここも同様です。

2023-02-28 00:45 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
>          }
ここは何をしているのか教えていただきたいです。

2023-02-28 00:45 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        private void DisposeLoginRetryHandler(bool clearOnly)
`Multiplay` と同じようにオプション引数にして、デフォルトは `true` にした方がいいと思います。

2023-02-28 00:45 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            connectAsyncs.Remove(channelId);
この処理順ではログインが切れたときにチャンネルから退出しておく（ログイン再接続後のチャンネル接続の自動復旧から除外する）ことができないのではないしょうか？

2023-02-28 00:45 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                }
`connectAsyncs` にこの関数デリゲートが入っていた場合、ここで削除しないとずっとゴミが溜まったままになってしまうと思います。

2023-02-28 06:14 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
>          }
チャンネル接続の自動回復をおこなうときに複数回ログイン処理が呼ばれるのを防いでいる。

2023-02-28 06:34 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            connectAsyncs.Remove(channelId);
修正し、テストが通ることも確認しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/15/commits/d2fde6ace0dfd6048d0cc75eb188339c43ca682b

2023-02-28 06:35 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                }
修正し、テストが通ることも確認しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/15/commits/8674be6a1f0bca14858b2d842e03ae0ad0b17de5

2023-02-28 06:40 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +                }
thx

2023-02-28 06:40 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            connectAsyncs.Remove(channelId);
thx

2023-02-28 06:43 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +        /// Arg: Final results of retry. True for success, false for failure.
Fixed!
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/15/commits/08947d80ee3706a3d5fb4ef431faaa4c9d54aa52

2023-02-28 06:46 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +        private bool isLoginBlocking;
Fixed!
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/15/commits/821208200c7ceea40602929d0cca470763c5c7e7

2023-02-28 06:50 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +        private void DisposeLoginRetryHandler(bool clearOnly)
Fixed!
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/15/commits/449437bf54c3d6d90a84a0d69b1b4f70bbec05f4

2023-02-28 06:58 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        /// Arg: Final results of retry. True for success, false for failure.
確認しました！

2023-02-28 06:59 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        private bool isLoginBlocking;
確認しました！

2023-02-28 07:01 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        private void DisposeLoginRetryHandler(bool clearOnly)
すみません、私のミスです。
デフォルトは `false` がいいと思います。

2023-02-28 07:55 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +        private void DisposeLoginRetryHandler(bool clearOnly)
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/15/commits/0719f3c9c8a7bfad29e0af39e18b011979ffa97e

2023-02-28 08:03 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        private void DisposeLoginRetryHandler(bool clearOnly)
確認しました！

2023-02-28 08:03 UTC, sus-taguchi-t approved these changes

2023-02-28 08:03 UTC, merged