【IntegrationFW利用者がVivoxを使えるようにする
extreal-dev/Extreal.Integration.Chat.Vivox pull request #2
Opened 2022-11-28 02:38 UTC by sus-taguchi-t

close #1 

# Describe Your Changes (なんの変更を加えましたか?)

- フォーマッタを導入しました
- 静的解析を導入しました
- Chat ライブラリを実装しました
- Chat のテストを実装しました
- テスト方法を README に記述しました

# What did you verify? (何を確認しましたか?)

- [x] Verified that processing for invalid arguments and invalid method calls is included (無効な引数や無効なメソッド呼び出しに対する処理が入っていることを確認しました)
- [x] Verified that debug logs are being output to show behavior at runtime (実行時の動作が分かるようなデバッグログを出力していることを確認しました)
- [x] Verified that no problems were found in the static analysis (静的解析で問題が見つからないことを確認しました)
- [x] Verified that all tests succeeded (全てのテストが成功することを確認しました)
- [x] Verified that test coverage is 100% (テストカバレッジが100%になることを確認しました)
- [ ] Verified that the C# document is written for all Pulic API (すべての公開 API に対して C# ドキュメントが書かれていることを確認しました)
- [ ] Verified that the Assembly Definition does not include Analyzer (アセンブリ定義がアナライザを含んでいないことを確認しました)

# Message to reviewers (レビュアーへのメッセージ)

- [ ] コードは読みやすいですか？
- [ ] 改善点はありますか？

2022-11-28 05:38 UTC, kiyohome requested changes

2022-11-28 05:38 UTC, kiyohome commented on Tests/Runtime/VivoxClientTest.cs
> +        public IEnumerator LogoutSuccess() => UniTask.ToCoroutine(async () =>
落ちますね。
```
LogoutSuccess (3.839s)
---
Unhandled log message: '[Error] <Login>b__0: vx_req_account_anonymous_login_t failed: VivoxUnity.VivoxApiException: Name Resolution Failed (10006)
  at VivoxUnity.VxClient.EndIssueRequest (System.IAsyncResult result) [0x0004c] in C:\Users\kiyoh\work\xr\Extreal.Dev\Library\PackageCache\com.unity.services.vivox@15.1.190000-pre.1\Runtime\VivoxUnity\VxClient.cs:232 
  at VivoxUnity.Private.LoginSession+<>c__DisplayClass97_0.<Login>b__0 (System.IAsyncResult result) [0x00002] in C:\Users\kiyoh\work\xr\Extreal.Dev\Library\PackageCache\com.unity.services.vivox@15.1.190000-pre.1\Runtime\VivoxUnity\Private\LoginSession.cs:496 '. Use UnityEngine.TestTools.LogAssert.Expect
---
VivoxUnity.VivoxDebug:DebugMessage (object,vx_log_level) (at Library/PackageCache/com.unity.services.vivox@15.1.190000-pre.1/Runtime/VivoxUnity/VivoxDebug.cs:87)
VivoxUnity.VivoxDebug:VxExceptionMessage (string) (at Library/PackageCache/com.unity.services.vivox@15.1.190000-pre.1/Runtime/VivoxUnity/VivoxDebug.cs:45)
VivoxUnity.Private.LoginSession/<>c__DisplayClass97_0:<Login>b__0 (System.IAsyncResult) (at Library/PackageCache/com.unity.services.vivox@15.1.190000-pre.1/Runtime/VivoxUnity/Private/LoginSession.cs:501)
VivoxUnity.AsyncResult`1<vx_resp_base_t>:SetComplete (vx_resp_base_t) (at Library/PackageCache/com.unity.services.vivox@15.1.190000-pre.1/Runtime/VivoxUnity/AsyncResult.cs:120)
VivoxUnity.VxClient:InstanceOnMainLoopRun (bool&) (at Library/PackageCache/com.unity.services.vivox@15.1.190000-pre.1/Runtime/VivoxUnity/VxClient.cs:167)
MessagePump:RunOnce () (at Library/PackageCache/com.unity.services.vivox@15.1.190000-pre.1/Runtime/VivoxUnity/MessagePump.cs:73)
MessagePump:RunUntil (LoopDone) (at Library/PackageCache/com.unity.services.vivox@15.1.190000-pre.1/Runtime/VivoxUnity/MessagePump.cs:56)
VivoxUnity.Client:RunOnce () (at Library/PackageCache/com.unity.services.vivox@15.1.190000-pre.1/Runtime/VivoxUnity/Client.cs:298)
VivoxUnity.VxUnityInterop/<VivoxUnityRun>d__6:MoveNext () (at Library/PackageCache/com.unity.services.vivox@15.1.190000-pre.1/Runtime/VivoxUnity/VxUnityInterop.cs:66)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)
---
[Debug:VivoxClient] Initialize VivoxClient
[Debug:VivoxClient] This client is logging in
<Login>b__0: vx_req_account_anonymous_login_t failed: VivoxUnity.VivoxApiException: Name Resolution Failed (10006)
  at VivoxUnity.VxClient.EndIssueRequest (System.IAsyncResult result) [0x0004c] in C:\Users\kiyoh\work\xr\Extreal.Dev\Library\PackageCache\com.unity.services.vivox@15.1.190000-pre.1\Runtime\VivoxUnity\VxClient.cs:232 
  at VivoxUnity.Private.LoginSession+<>c__DisplayClass97_0.<Login>b__0 (System.IAsyncResult result) [0x00002] in C:\Users\kiyoh\work\xr\Extreal.Dev\Library\PackageCache\com.unity.services.vivox@15.1.190000-pre.1\Runtime\VivoxUnity\Private\LoginSession.cs:496 
Error: Name Resolution Failed (10006)
[Debug:VivoxClient] Dispose VivoxClient
VivoxApi::CommandHandler::~CommandHandler(358)EventLog: saved to `C:\Users\kiyoh\AppData\Local\Vivox\Unity.xml`
```

2022-11-28 05:38 UTC, kiyohome commented on Tests/Runtime/VivoxClientTest.cs
> +        public IEnumerator SendMessageSuccess() => UniTask.ToCoroutine(async () =>
LogoutSuccessが落ちているからなのか、このテストが実行中で止まって、放置しておくとEditorが固まります（無応答）
```
SendMessageSuccess (0.000s)
---
Cancelled by user
---
[Debug:VivoxClient] Initialize VivoxClient
[Debug:VivoxClient] This client is logging in
[Debug:VivoxClient] RecoveryState was changed to Connected
[Debug:VivoxClient] This client logged in
[Debug:VivoxClient] This client is logging out
[Debug:VivoxClient] Unable to connect before login
[Debug:VivoxClient] This client logged out
```
放置せず止まったら実行を止めた時のログです。

2022-11-28 07:11 UTC, kiyohome requested changes

2022-11-28 07:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +        public async UniTask InitializeAsync(VivoxConnectionConfig config)
configを受け取るコンストラクタでいいと思いました。
UGS対応でconfig不要になった場合は
https://vcontainer.hadashikick.jp/ja/registering/register-using-delegate
で登録することにするのはどうでしょうか？

2022-11-28 07:11 UTC, kiyohome commented on Runtime/VivoxConnectionConfig.cs
> +    public class VivoxConnectionConfig : ScriptableObject
VivoxConfigという名前でよくないでしょうか？
Connection以外の設定を追加したくなってもできないので。

2022-11-28 07:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +        public string[] AvailableInputDevices
clientを公開すればいいと思ったんですが、このあたりは何で設けてるんですかね？
```
        public string[] AvailableInputDevices
            => client.AudioInputDevices?.AvailableDevices.Select(device => device.Name).ToArray();
        public string ActiveInputDevice => client.AudioInputDevices?.ActiveDevice.Name;
        public string[] AvailableOutputDevices
            => client.AudioOutputDevices?.AvailableDevices.Select(device => device.Name).ToArray();
        public string ActiveOutputDevice => client.AudioOutputDevices?.ActiveDevice.Name;
```

2022-11-28 07:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +        private Client client;
Clientを取得できないとExtrealで公開してないことをやりたい場合につらくないでしょうか？

2022-11-28 07:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +        private LoginState LoginState => loginSession != null ? loginSession.State : LoginState.LoggedOut;
LoginStateの大部分は
ログインしている？
ログアウトしている？
の判定処理に使ってると思うので
そういうプロパティを用意して判定ロジックを1つにした方がいいと思います。

2022-11-28 07:11 UTC, kiyohome commented on Runtime/VivoxConnectionConfig.cs
> +    public class VivoxConnectionConfig : ScriptableObject
VivoxAppConfigですかね？

2022-11-28 07:11 UTC, kiyohome commented on Runtime/VivoxConnectionParameter.cs
> +    public struct VivoxConnectionParameter
Parameterは抽象的過ぎるのでできれば使いたくないです。
VivoxChannelConfigでどうでしょうか？

2022-11-28 07:11 UTC, kiyohome commented on Runtime/VivoxLoginParameter.cs
> +    public struct VivoxLoginParameter
こちらもParameterを外したいです。
VivoxAuthConfigでいかがでしょうか？

2022-11-28 07:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            onLoggedIn.Dispose();
CompositeDisposableでまとめてやった方がよくないでしょうか？

2022-11-28 07:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +        public async UniTask InitializeAsync(VivoxConnectionConfig config)
コンストラクタでInitializeAsyncやりたいですね。
initializeチェックの処理がすべて削除できるので。

2022-11-28 07:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +                return;
これだとログインした前提でアプリの処理が進まないでしょうか？
falseとか返した方がよくないでしょうか？

2022-11-28 07:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +                    Logger.LogDebug("This client already logged into the server");
LoggingInも含まれてますが`already logged into`で整合性取れてますか？

2022-11-28 08:13 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +        private Client client;
このあたりとか。
https://docs.vivox.com/v5/general/unity/15_1_180000/ja-jp/Default.htm#access-token-guide/override-development-key-generation.htm%3FTocPath%3DVivox%2520Unity%2520SDK%2520%25E3%2581%25AE%25E3%2583%2589%25E3%2582%25AD%25E3%2583%25A5%25E3%2583%25A1%25E3%2583%25B3%25E3%2583%2588%7C%25E3%2582%25A2%25E3%2582%25AF%25E3%2582%25BB%25E3%2582%25B9%25E3%2583%2588%25E3%2583%25BC%25E3%2582%25AF%25E3%2583%25B3%25E9%2596%258B%25E7%2599%25BA%25E8%2580%2585%25E3%2582%25AC%25E3%2582%25A4%25E3%2583%2589%7C_____10

2022-11-28 08:49 UTC, kiyohome requested changes

2022-11-28 08:49 UTC, kiyohome commented on Runtime/ChatCapability.cs
> +    public enum ChatCapability
ChatTypeがしっくりきます。

2022-11-28 09:33 UTC, sus-taguchi-t commented on Tests/Runtime/VivoxClientTest.cs
> +        public IEnumerator LogoutSuccess() => UniTask.ToCoroutine(async () =>
直前でインターネット接続を切断するため、これが回復する前にこのテストが走って落ちている気がします。
インターネット接続が回復してから充分時間が経ってから次のテストに入るように変更します。

2022-11-28 09:34 UTC, sus-taguchi-t commented on Tests/Runtime/VivoxClientTest.cs
> +        public IEnumerator SendMessageSuccess() => UniTask.ToCoroutine(async () =>
LogoutSuccessが落ちているのが原因と推定されます。
修正したので、まだ落ちるようであればお手数ですがまたお知らせいただけると嬉しいです。

2022-11-28 09:39 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        public async UniTask InitializeAsync(VivoxConnectionConfig config)
そうします。

2022-11-28 09:40 UTC, sus-taguchi-t commented on Runtime/VivoxConnectionConfig.cs
> +    public class VivoxConnectionConfig : ScriptableObject
そうします。

2022-11-28 09:41 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        public string[] AvailableInputDevices
`client` を公開するようにします。

2022-11-28 09:42 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        private Client client;
`client` を公開するようにします。

2022-11-28 09:42 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        private LoginState LoginState => loginSession != null ? loginSession.State : LoginState.LoggedOut;
そうします。

2022-11-28 10:40 UTC, sus-taguchi-t commented on Runtime/VivoxConnectionParameter.cs
> +    public struct VivoxConnectionParameter
そうします。

2022-11-28 10:41 UTC, sus-taguchi-t commented on Runtime/VivoxLoginParameter.cs
> +    public struct VivoxLoginParameter
そうします。

2022-11-28 10:49 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            onLoggedIn.Dispose();
まとめてやると `CC0033` の静的解析が各フィールドに対して「`Dispose()` を呼び出してください」と怒ります。
`.editorconfig` から警告を抑制しますか？

2022-11-28 10:50 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            onLoggedIn.Dispose();
まとめてやると `CC0033` の静的解析が各フィールドに対して「`Dispose()` を呼び出してください」と怒りました。
そうやら `CompositeDisposable` に追加して一気に破棄しようとすると CodeCracker はそれを検知しないようです。
`.editorconfig` から警告を抑制しますか？

2022-11-28 10:51 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                return;
イベント通知ありきで処理を進めてもらうことを考えています。

2022-11-28 10:52 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                    Logger.LogDebug("This client already logged into the server");
`logging/logged` という形でログが出力されるようにします。

2022-11-28 10:53 UTC, sus-taguchi-t commented on Runtime/ChatCapability.cs
> +    public enum ChatCapability
そうします。

2022-11-28 10:56 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        private Client client;
併せて `LoginSession` も公開するようにします。

2022-11-29 03:05 UTC, sus-taguchi-t commented on Tests/Runtime/VivoxClientTest.cs
> +        public IEnumerator LogoutSuccess() => UniTask.ToCoroutine(async () =>
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f7fc14de516f2e4a8a929d3a2ebbaf113a00270a

2022-11-29 03:06 UTC, sus-taguchi-t commented on Tests/Runtime/VivoxClientTest.cs
> +        public IEnumerator SendMessageSuccess() => UniTask.ToCoroutine(async () =>
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f7fc14de516f2e4a8a929d3a2ebbaf113a00270a

2022-11-29 03:07 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        public async UniTask InitializeAsync(VivoxConnectionConfig config)
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f7fc14de516f2e4a8a929d3a2ebbaf113a00270a修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f7fc14de516f2e4a8a929d3a2ebbaf113a00270a

2022-11-29 03:08 UTC, sus-taguchi-t commented on Runtime/VivoxConnectionConfig.cs
> +    public class VivoxConnectionConfig : ScriptableObject
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f7fc14de516f2e4a8a929d3a2ebbaf113a00270a

2022-11-29 03:08 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        public string[] AvailableInputDevices
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f7fc14de516f2e4a8a929d3a2ebbaf113a00270a

2022-11-29 03:08 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        private Client client;
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f7fc14de516f2e4a8a929d3a2ebbaf113a00270a

2022-11-29 03:08 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        private LoginState LoginState => loginSession != null ? loginSession.State : LoginState.LoggedOut;
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f7fc14de516f2e4a8a929d3a2ebbaf113a00270a

2022-11-29 03:08 UTC, sus-taguchi-t commented on Runtime/VivoxConnectionParameter.cs
> +    public struct VivoxConnectionParameter
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f7fc14de516f2e4a8a929d3a2ebbaf113a00270a

2022-11-29 03:08 UTC, sus-taguchi-t commented on Runtime/VivoxLoginParameter.cs
> +    public struct VivoxLoginParameter
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f7fc14de516f2e4a8a929d3a2ebbaf113a00270a

2022-11-29 03:09 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                    Logger.LogDebug("This client already logged into the server");
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f7fc14de516f2e4a8a929d3a2ebbaf113a00270a

2022-11-29 03:09 UTC, sus-taguchi-t commented on Runtime/ChatCapability.cs
> +    public enum ChatCapability
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f7fc14de516f2e4a8a929d3a2ebbaf113a00270a

2022-11-29 03:11 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        }
送信失敗したチャンネルの ID を返させるようにしました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/a7242f2d0273a4fb694a15b3b2cc400be94c7ec5

2022-11-29 06:11 UTC, kiyohome requested changes

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +        public void SendTextMessage
失敗したクライアントIDを返しときましょう。

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +        public void MuteInputDevice(bool muted)
initializedがなくなるとメソッドもいらないですね。

2022-11-29 06:11 UTC, kiyohome commented on Runtime/ChatCapability.cs
> +    public enum ChatType
ファイル名がChatCapabilityのままです。

2022-11-29 06:11 UTC, kiyohome commented on Runtime/Extreal.Integration.Chat.Vivox.asmdef
> +        "Extreal.Framework.Analyzer"
これは最後に削除しますよね。
マージブロック目的でコメントしときます。

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxAppConfig.cs
> +#pragma warning disable CC0052
初期値の指定を無くすのはどうでしょうか？
ガイドやドキュメントコメントでVivox Developer Portalの値を指定して、と説明すると思うのでなくしても大丈夫だと思います。

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxAuthConfig.cs
> +        public VivoxAuthConfig(string displayName, string accountName = default, byte tokenExpirationDuration = 60)
質問です。byteにしている理由はありますか？

https://learn.microsoft.com/ja-jp/dotnet/csharp/language-reference/builtin-types/integral-numeric-types

byteは表現できる数値が少なく感じました。
uintやulongでなくていいのかなと思いました。

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxChannelConfig.cs
> +            if (!Enum.IsDefined(typeof(ChatType), chatType))
Enumのこのチェックは必要ですか？
実装ミスなどで発生するものでしょうか？

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            onTextMessageReceived.OnNext(new VivoxReceivedValue<string>(accountName, channelName, message));
IChannelTextMessageを返せばいいと思うんですが、VivoxReceivedValueを返している理由はありますか？
ここで返していなものを使いたくなるかは分かりませんが制限する必要はないかなと思いました。

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            if (value is < (-50) or > 50)
()付けてる理由ありますか？

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            if ((propertyChangedEventArgs.PropertyName is "AudioState" or "TextState")
()付けてる理由ありますか？

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            if (positionalChannelSession?.Channel == channelId)
==
`Possible unintended reference comparison. To get a value comparison, use 'Equals' method.`
と言われてます。

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +        private readonly VivoxAppConfig config;
色々なconfigあるのでappConfigに統一した方が分かりやすくないでしょうか？
コンストラクタのconfigも。

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            if (!CheckManualCredentials(config))
boolにするならIsValidManualCredentialsとかですが、そもそもcheckメソッドの中で例外を投げればよいかと思います。
コンストラクタの処理としてはこの例外送出がメイン処理ではないので。

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +                    channelSession.PropertyChanged -= OnChannelPropertyChanged;
privateメソッドにEventHandlerの設定/解除処理を切り出して近くに並んでると嬉しいです。
```
private void AddChannelSessionEventHandler(ChannnelSession channnelSession)
private void RemoveChannelSessionEventHandler(ChannnelSession channnelSession)
private void AddLoginSessionEventHandler(LoginSession loginSession)
private void RmoveLoginSessionEventHandler(LoginSession loginSession)
```

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            if (Client != null)
`Client?.Uninitialize();`
は使わない方がいいでしょうか？

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            if (Application.internetReachability == NetworkReachability.NotReachable)
インターネットにつながっているか？チェックですよね？
Extrealに共通のUtilsが欲しいですね。

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +                    Logger.LogDebug("This computer is not connected to the Internet");
細かいですがcomputerよりdeviceの方がよくないでしょうか？

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            var issuer = config.Issuer;
一度変数に格納しているのは何か理由ありますか？
どのconfigがどこで使われているか追いにくくなっているので意図がなければ格納しない方がいいと思いました。

```
            var accountId = new AccountId(config.Issuer, authConfig.AccountName, config.Domain, authConfig.DisplayName);
            LoginSession = Client.GetLoginSession(accountId);
            var tokenExpirationDuration = TimeSpan.FromSeconds(authConfig.TokenExpirationDuration);
            var loginToken = LoginSession.GetLoginToken(config.TokenKey, tokenExpirationDuration);
```

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +                    Logger.LogDebug("This client already logged out of the server");
細かいのですが`logging out`が含まれませんか？

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            if (!IsLoggingIn && !IsLoggedIn)
IsLoggingInの時はLogoutを実行した方がよくないでしょうか？
できるだけLogoutできる方に倒さなくてよいですかね？

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            var issuer = config.Issuer;
ここのたくさんある変数もない方が分かりやすくないでしょうか？

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            var activeChannelIds = ActiveChannelSessions.Keys.ToArray();
これ直接呼び出した方がよくないでしょうか？
```
LoginSession?.ChannelSessions.ToList().ForEach(cs => cs.Disconnect());
```

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            return true;
あまり分かってないような気がしますが、こちらはtrueを返した時点で送信が成功した、ということでしょうか？
それとも送信を試みた、ということでしょうか？

LoginやConnectは返してないので気になりました。

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            if (value is < (-50) or > 50)
値のrangeチェックしかしてないのですが必要でしょうか？
volumeなので値の仕様を知らないと設定できない気がしたので。

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            if (value is < (-50) or > 50)
muteの設定やこちらのメソッドはHolidayのModelにあると良い気がしました。

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +        public void Update3DPosition
こちらもHolidayのModelなのかな、と思いました。

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            await RefreshAudioDevicesAsync();
Refreshについて今度教えてください。

2022-11-29 06:11 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +                onAudioEnergyChanged.OnNext(new VivoxReceivedValue<double>(accountName, channelName, audioEnergy));
IParticipantとAudioEnergyのdoubleを返せばいいんですかね？
ところでこれはアプリでどんな感じで使うんですかね？

2022-11-29 06:18 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            onLoggedIn.Dispose();
Dispose漏れは避けたいのでpragmaを入れるか、個別にdisposeを書きますか。

2022-11-29 06:22 UTC, sus-taguchi-t commented on Runtime/ChatCapability.cs
> +    public enum ChatType
すみません、修正します。

2022-11-29 06:24 UTC, sus-taguchi-t commented on Runtime/VivoxAppConfig.cs
> +#pragma warning disable CC0052
良いと思います。
そうすれば `pragma` が取れますね。

2022-11-29 06:27 UTC, sus-taguchi-t commented on Runtime/VivoxAuthConfig.cs
> +        public VivoxAuthConfig(string displayName, string accountName = default, byte tokenExpirationDuration = 60)
トークンの有効期限を長く設定する必要はないと思ったので最小限のバイト数で指定しています。
特に vivox 側もこの `TokenExpitationDuration` を指定しなかった場合のデフォルトは 60 秒で設定されています。

2022-11-29 06:28 UTC, sus-taguchi-t commented on Runtime/VivoxChannelConfig.cs
> +            if (!Enum.IsDefined(typeof(ChatType), chatType))
実装ミスで発生します。
`Enum.Parse<ChatType>(/* any number */)` でこの if 文内に入れます。
ただ普通はこのような実装はしないとは思っています。

2022-11-29 06:30 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            onTextMessageReceived.OnNext(new VivoxReceivedValue<string>(accountName, channelName, message));
`IChannelTextMessage` で良いと思います。
修正します。

2022-11-29 06:31 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            if (value is < (-50) or > 50)
静的解析に従ったらこれが導入されていました。
深い意味はないので外します。

2022-11-29 06:43 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            if ((propertyChangedEventArgs.PropertyName is "AudioState" or "TextState")
結合の優先度が分かっていませんでした。
`is` 演算子の方が優先度が高そうなので外します。

2022-11-29 06:46 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            if (positionalChannelSession?.Channel == channelId)
すみません、修正します。

2022-11-29 06:54 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        private readonly VivoxAppConfig config;
確かにそうですね。
修正します。

2022-11-29 06:56 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            if (!CheckManualCredentials(config))
すみません、修正します。

2022-11-29 07:00 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                    channelSession.PropertyChanged -= OnChannelPropertyChanged;
そうします。

2022-11-29 07:08 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            if (Client != null)
使っても大丈夫です。
使用します。

2022-11-29 07:09 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            if (Application.internetReachability == NetworkReachability.NotReachable)
正確にはインターネットに接続できる可能性があるかのチェックです。
実際につながっているかどうかは保証されません。

2022-11-29 07:10 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                    Logger.LogDebug("This computer is not connected to the Internet");
そうします。

2022-11-29 07:14 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            var issuer = config.Issuer;
1 行の文字数を減らすことが目的でした。
格納しない方式に修正します。

2022-11-29 07:16 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                    Logger.LogDebug("This client already logged out of the server");
ログに追加します。

2022-11-29 07:17 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            if (!IsLoggingIn && !IsLoggedIn)
`IsLoggingIn` のときに `Logout()` を叩いてもログアウトはできないです。

2022-11-29 07:20 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            onLoggedIn.Dispose();
pragmaにしましょう

2022-11-29 07:39 UTC, kiyohome commented on Runtime/VivoxAuthConfig.cs
> +        public VivoxAuthConfig(string displayName, string accountName = default, byte tokenExpirationDuration = 60)
Vivoxに合わせてTimeSpanにしましょう。

2022-11-29 07:42 UTC, kiyohome commented on Runtime/VivoxChannelConfig.cs
> +            if (!Enum.IsDefined(typeof(ChatType), chatType))
普通に使って発生しないのであればチェックはやめときましょう。

2022-11-29 08:15 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            var activeChannelIds = ActiveChannelSessions.Keys.ToArray();
Disconnectと削除している処理を下記の呼び出しでいけそうであれば変更する。
LoginSession.DeleteChannelSession

動的になくなる可能性があるのでActiveChannelSessions[channelId]で取得した値をそのまま使うとnullになる可能性があるので対応する。LoginSession#GetChannnelSessionを使うとか。

2022-11-29 08:21 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            return true;
成功有無や失敗したクライアントIDを返すのをやめましょう。

2022-11-29 08:27 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            await RefreshAudioDevicesAsync();
getも用意しましょう。

2022-11-29 08:29 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +                onAudioEnergyChanged.OnNext(new VivoxReceivedValue<double>(accountName, channelName, audioEnergy));
タプルで2つを返しましょう。

2022-11-29 08:46 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            if (value is < (-50) or > 50)
そうですね。
削除します。

2022-11-29 08:46 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        public void Update3DPosition
そうですね。
削除します。

2022-11-29 08:54 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            if (value is < (-50) or > 50)
メソッド自体を削除します。

2022-11-29 08:55 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            if (positionalChannelSession?.Channel == channelId)
`positionalChannelSession` を保持しておく必要がなくなったので、この if 文自体を削除します。

2022-11-29 09:01 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            if (!IsLoggingIn && !IsLoggedIn)
`LoginSession == null` のときに `InvalidOperationException`  を投げるようにします。

2022-11-29 09:04 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            var issuer = config.Issuer;
なくします。

2022-11-29 11:32 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            var activeChannelIds = ActiveChannelSessions.Keys.ToArray();
`LoginSession.DeleteChannelSession()` は引数に存在しないチャンネルの `ChannelId` を投げてもエラーを吐かなかったため、エラーハンドリングは全体的になくしました。

2022-11-29 11:44 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                    Logger.LogDebug("This client already logged out of the server");
`LoginSession == null` のときにログを出力してリターンするようにするので、ログは
```
This client has never logged into the server before
```
に変更します。

2022-11-29 11:48 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            onLoggedIn.Dispose();
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:48 UTC, sus-taguchi-t commented on Runtime/ChatCapability.cs
> +    public enum ChatType
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:48 UTC, sus-taguchi-t commented on Runtime/VivoxAppConfig.cs
> +#pragma warning disable CC0052
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:48 UTC, sus-taguchi-t commented on Runtime/VivoxAuthConfig.cs
> +        public VivoxAuthConfig(string displayName, string accountName = default, byte tokenExpirationDuration = 60)
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:48 UTC, sus-taguchi-t commented on Runtime/VivoxChannelConfig.cs
> +            if (!Enum.IsDefined(typeof(ChatType), chatType))
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:49 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            onTextMessageReceived.OnNext(new VivoxReceivedValue<string>(accountName, channelName, message));
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:49 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            if (value is < (-50) or > 50)
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:49 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            if ((propertyChangedEventArgs.PropertyName is "AudioState" or "TextState")
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:49 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            if (positionalChannelSession?.Channel == channelId)
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:49 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        private readonly VivoxAppConfig config;
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:49 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            if (!CheckManualCredentials(config))
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:49 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                    channelSession.PropertyChanged -= OnChannelPropertyChanged;
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:49 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            if (Client != null)
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:49 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                    Logger.LogDebug("This computer is not connected to the Internet");
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:49 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            var issuer = config.Issuer;
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:50 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                    Logger.LogDebug("This client already logged out of the server");
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:50 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            if (!IsLoggingIn && !IsLoggedIn)
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:50 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            var issuer = config.Issuer;
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:50 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            var activeChannelIds = ActiveChannelSessions.Keys.ToArray();
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:50 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            return true;
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:50 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            if (value is < (-50) or > 50)
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:50 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        public void Update3DPosition
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:50 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            await RefreshAudioDevicesAsync();
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-29 11:50 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                onAudioEnergyChanged.OnNext(new VivoxReceivedValue<double>(accountName, channelName, audioEnergy));
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/f352b4244d2b9fafb38f8c9e2256785dd56726b8

2022-11-30 07:52 UTC, kiyohome commented on Tests/Runtime/VivoxClientTest.cs
> +        public IEnumerator LogoutSuccess() => UniTask.ToCoroutine(async () =>
通りました！

2022-11-30 07:52 UTC, kiyohome commented on Tests/Runtime/VivoxClientTest.cs
> +        public IEnumerator SendMessageSuccess() => UniTask.ToCoroutine(async () =>
通りました！

2022-11-30 07:54 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            onLoggedIn.Dispose();
LGTM

2022-11-30 07:54 UTC, kiyohome commented on Runtime/ChatCapability.cs
> +    public enum ChatType
LGTM

2022-11-30 07:56 UTC, kiyohome commented on Runtime/VivoxAuthConfig.cs
> +        public VivoxAuthConfig(string displayName, string accountName = default, byte tokenExpirationDuration = 60)
LGTM

2022-11-30 07:56 UTC, kiyohome commented on Runtime/VivoxChannelConfig.cs
> +            if (!Enum.IsDefined(typeof(ChatType), chatType))
LGTM

2022-11-30 08:00 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            onTextMessageReceived.OnNext(new VivoxReceivedValue<string>(accountName, channelName, message));
LGTM

2022-11-30 08:00 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            if (value is < (-50) or > 50)
LGTM

2022-11-30 08:00 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            if ((propertyChangedEventArgs.PropertyName is "AudioState" or "TextState")
LGTM

2022-11-30 08:02 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            if (positionalChannelSession?.Channel == channelId)
LGTM

2022-11-30 08:04 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +        private readonly VivoxAppConfig config;
LGTM

2022-11-30 08:05 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            if (!CheckManualCredentials(config))
LGTM

2022-11-30 08:05 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +                    channelSession.PropertyChanged -= OnChannelPropertyChanged;
LGTM

2022-11-30 08:06 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            if (Client != null)
LGTM

2022-11-30 08:06 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            if (Application.internetReachability == NetworkReachability.NotReachable)
('◇')ゞ

2022-11-30 08:07 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +                    Logger.LogDebug("This computer is not connected to the Internet");
LGTM

2022-11-30 11:28 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            var issuer = config.Issuer;
LGTM

2022-11-30 11:28 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +                    Logger.LogDebug("This client already logged out of the server");
LGTM

2022-11-30 11:28 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            if (!IsLoggingIn && !IsLoggedIn)
LGTM

2022-11-30 11:29 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            var issuer = config.Issuer;
LGTM

2022-11-30 11:30 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            var activeChannelIds = ActiveChannelSessions.Keys.ToArray();
LGTM

2022-11-30 11:30 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            return true;
LGTM

2022-11-30 11:30 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            if (value is < (-50) or > 50)
LGTM

2022-11-30 11:30 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +        public void Update3DPosition
LGTM

2022-11-30 11:30 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            await RefreshAudioDevicesAsync();
LGTM

2022-11-30 11:31 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +                onAudioEnergyChanged.OnNext(new VivoxReceivedValue<double>(accountName, channelName, audioEnergy));
LGTM

2022-12-01 06:58 UTC, kiyohome requested changes

2022-12-01 06:58 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            var outputAsyncResult = Client.AudioInputDevices.BeginRefresh(Client.AudioInputDevices.EndRefresh);
Outputでは？

2022-12-01 07:25 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            var outputAsyncResult = Client.AudioInputDevices.BeginRefresh(Client.AudioInputDevices.EndRefresh);
すみません、その通りです。
修正します。

2022-12-01 07:39 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +            var outputAsyncResult = Client.AudioInputDevices.BeginRefresh(Client.AudioInputDevices.EndRefresh);
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/fed47cabe44c2a67c825ea59f5efc393a6fff2bf

2022-12-02 02:03 UTC, sus-taguchi-t commented on Runtime/VivoxAppConfig.cs
> +        public string SecretKey => secretKey;
`TokenKey` -> `SecretKey`
と変更しました。vivox の API 情報に寄せるためです。
この変更を確定する場合はガイドのクラス図を修正する必要があります。

2022-12-02 03:53 UTC, kiyohome requested changes

2022-12-02 03:53 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +                throw new ArgumentNullException(nameof(channelId));
ドキュメントコメンが漏れている？

2022-12-02 03:53 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +        public async UniTask<IAudioDevice> GetActiveAudioInputDeviceAsync()
Client.AudioInputDevicesを取得するメソッドでなく、
Client.AudioInputDevices.ActiveDevice
Client.AudioInputDevices.AvailableDevices
を取得するメソッドにしているのは何かわけがあるのでしょうか？

2022-12-02 03:53 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +            var outputAsyncResult = Client.AudioInputDevices.BeginRefresh(Client.AudioInputDevices.EndRefresh);
LGTM

2022-12-02 04:06 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                throw new ArgumentNullException(nameof(channelId));
すみません、漏れていました。
追記します。

2022-12-02 04:18 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        public async UniTask<IAudioDevice> GetActiveAudioInputDeviceAsync()
特にないです。
`AudioInputDevices` を取得する形で修正します。

2022-12-02 06:36 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                throw new ArgumentNullException(nameof(channelId));
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/fd3210c99f48bc477333abe8ef4c58b5bc1f8045

2022-12-02 06:36 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        public async UniTask<IAudioDevice> GetActiveAudioInputDeviceAsync()
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/048503e40818e6a561c0a1a010128bd9577b6d23

2022-12-02 06:38 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +        public async UniTask SetActiveAudioInputDeviceAsync(IAudioDevice device)
`SetAudioInputDeviceAsync` -> `SetActiveAudioInputDeviceAsync`
メソッド名を見直しました。
（`SetActiveAudioOutputDeviceAsync` も同様）

2022-12-02 06:47 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +                throw new ArgumentNullException(nameof(channelId));
LGTM

2022-12-02 06:48 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +        public async UniTask<IAudioDevice> GetActiveAudioInputDeviceAsync()
LGTM

2022-12-02 07:00 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +        public async UniTask SetActiveAudioInputDeviceAsync(IAudioDevice device)
LGTM

2022-12-02 07:01 UTC, kiyohome approved these changes

2022-12-02 07:03 UTC, sus-taguchi-t commented on Runtime/Extreal.Integration.Chat.Vivox.asmdef
> +        "Extreal.Framework.Analyzer"
削除しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/2/commits/10ea7043a1307b13d01b81ee11c1d6370b8e3618

2022-12-02 07:05 UTC, kiyohome commented on Runtime/Extreal.Integration.Chat.Vivox.asmdef
> +        "Extreal.Framework.Analyzer"
LGTM

2022-12-02 07:06 UTC, merged