OnUserConnected イベントの修正
extreal-dev/Extreal.Integration.Chat.Vivox pull request #7
Opened 2022-12-23 08:42 UTC by sus-taguchi-t

# Describe Your Changes (なんの変更を加えましたか?)

- Fixed `OnUserConnected` event (`OnUserConnected` イベントを修正した)
- Modified logs (ログを修正した)
- Modify test codes (テストコードを修正した)

# What did you verify? (何を確認しましたか?)

- [x] Verified that processing for invalid arguments and invalid method calls is included (無効な引数や無効なメソッド呼び出しに対する処理が入っていることを確認しました)
- [x] Verified that debug logs are being output to show behavior at runtime (実行時の動作が分かるようなデバッグログを出力していることを確認しました)
- [x] Verified that no problems were found in the static analysis (静的解析で問題が見つからないことを確認しました)
- [x] Verified that all tests succeeded (全てのテストが成功することを確認しました)
- [x] Verified that test coverage is 100% (テストカバレッジが100%になることを確認しました)

# Message to reviewers (レビュアーへのメッセージ)

- [ ] 何か気になる点はありますか？

2022-12-23 09:31 UTC, kiyohome requested changes

2022-12-23 09:31 UTC, kiyohome commented on Runtime/VivoxChannelConfig.cs
> +        /// Uses when login is not successful.
logingでなくてconnectではないですか？

2022-12-26 00:39 UTC, kiyohome requested changes

2022-12-26 00:39 UTC, kiyohome commented on Tests/Runtime/Sub/VivoxClientTestSub.cs
> +    public class VivoxClientTestSub
READMEのテスト方法を最新化しておいて欲しいです。
必要だったらサンプルのプレイ方法についても更新をお願いします。

2022-12-26 00:39 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +                    Logger.LogDebug($"A user disconnected from the channel '{channelName}'");
2回実行してみましたが、このelse文がカバレッジ未達でした？
最後にSubを実行してテストはすべてパスしてます。
何か特別な手順とかありますか？

2022-12-26 00:59 UTC, sus-taguchi-t commented on Runtime/VivoxChannelConfig.cs
> +        /// Uses when login is not successful.
すみません、その通りです。
修正します。

2022-12-26 00:59 UTC, sus-taguchi-t commented on Tests/Runtime/Sub/VivoxClientTestSub.cs
> +    public class VivoxClientTestSub
最新化します。

2022-12-26 01:00 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                    Logger.LogDebug($"A user disconnected from the channel '{channelName}'");
確かにメインだけでは未達です。
メインのみで通るように改変します。

2022-12-26 01:36 UTC, sus-taguchi-t commented on Runtime/VivoxChannelConfig.cs
> +        /// Uses when login is not successful.
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/7/commits/ef2c2836932e08a0c690900c4271e5af9814692e

2022-12-26 01:37 UTC, sus-taguchi-t commented on Runtime/VivoxClient.cs
> +                    Logger.LogDebug($"A user disconnected from the channel '{channelName}'");
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/7/commits/7ef51f84c7ea69b357393e657b2b7c8520cdb1b4

2022-12-26 01:37 UTC, sus-taguchi-t commented on Tests/Runtime/Sub/VivoxClientTestSub.cs
> +    public class VivoxClientTestSub
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/7/commits/f387461629806be66414f6906fa85850fb25a1b1

2022-12-26 02:12 UTC, sus-taguchi-t commented on Tests/Runtime/Sub/VivoxClientTestSub.cs
> +    public class VivoxClientTestSub
Sample の内容も古かったので更新しました。
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/7/commits/ccf849523eaf7fd37b06a100577859f8c76da739 https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/7/commits/d568ff81cc088a5bbb67ff87976f2d9f44c1be6a https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/7/commits/fcf9b552d416e3bab862526458bddce6a76a67ed

2022-12-26 02:15 UTC, sus-taguchi-t reviewed
以下 3 箇所の変更を追加で実施しました。
https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/7/commits/52c75ac0fc430876902b39622212e8281703a59f https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/7/commits/582902a9ea1151aae23d3d99a2fd019ef66e657e https://github.com/extreal-dev/Extreal.Integration.Chat.Vivox/pull/7/commits/37ef6fe5f50b55b6016af3924e5fef9df81bc60e

2022-12-26 04:05 UTC, kiyohome commented on Runtime/VivoxChannelConfig.cs
> +        /// Uses when login is not successful.
LGTM

2022-12-26 04:05 UTC, kiyohome commented on Tests/Runtime/Sub/VivoxClientTestSub.cs
> +    public class VivoxClientTestSub
LGTM

2022-12-26 04:05 UTC, kiyohome commented on Runtime/VivoxClient.cs
> +                    Logger.LogDebug($"A user disconnected from the channel '{channelName}'");
LGTM

2022-12-26 04:07 UTC, kiyohome approved these changes

2022-12-26 04:08 UTC, merged